//! Prefilters large device photos into upload-ready sizes at build time.
use std::fmt::Write as _;
use std::{env, fs, path::Path};

include!("src/filter.rs");

/// Common pixel densities, ascending; other densities use the next larger bake.
const DENSITIES: [f32; 2] = [1.0, 2.0];

/// Maximum painted enclosure height; keep aligned with `preview::ART_HEIGHT`.
const ENCLOSURE_HEIGHT: f32 = 330.0;

/// Device-list enclosure height, prefiltered to avoid shrinking the large bake.
const THUMBNAIL_HEIGHT: f32 = 30.0;

/// Asset stems and generated constants; all masters bake to one enclosure height.
const PHOTOS: [(&str, &str); 13] = [
    ("pro-x-superlight-black.png", "SUPERLIGHT"),
    ("pro-x-superlight-white.png", "SUPERLIGHT_WHITE"),
    ("pro-x-superlight-red.png", "SUPERLIGHT_RED"),
    ("pro-x-superlight-magenta.png", "SUPERLIGHT_MAGENTA"),
    ("pro-x-superlight-2-black.png", "SUPERLIGHT_2"),
    ("pro-x-superlight-2-white.png", "SUPERLIGHT_2_WHITE"),
    ("pro-x-superlight-2-magenta.png", "SUPERLIGHT_2_MAGENTA"),
    ("pro-x-superlight-2-cyan.png", "SUPERLIGHT_2_CYAN"),
    ("g305-lightspeed-black.png", "G305"),
    ("g305-lightspeed-white.png", "G305_WHITE"),
    ("g305-lightspeed-blue.png", "G305_BLUE"),
    ("g305-lightspeed-lilac.png", "G305_LILAC"),
    ("g305-lightspeed-mint.png", "G305_MINT"),
];

fn main() {
    let out_dir = env::var("OUT_DIR").expect("cargo sets OUT_DIR");
    let out_dir = Path::new(&out_dir);
    let mut table = String::from("// @generated by build.rs -- do not edit.\n");

    for (stem, name) in PHOTOS {
        let source = Path::new("../../assets/mouses").join(stem);
        println!("cargo::rerun-if-changed={}", source.display());

        let master = image::open(&source)
            .unwrap_or_else(|error| panic!("could not read {}: {error}", source.display()))
            .into_rgba32f();
        // Crop framing margins so all photos and coordinates use the enclosure itself.
        let bounds = enclosure(&master);
        let cropped =
            image::imageops::crop_imm(&master, bounds[0], bounds[1], bounds[2], bounds[3])
                .to_image();

        // A master that cannot fill the largest bake would be painted upscaled
        // on the buttons page, which shows on every edge of the enclosure.
        let largest = ENCLOSURE_HEIGHT * DENSITIES[DENSITIES.len() - 1];
        if (bounds[3] as f32) < largest {
            println!(
                "cargo::warning={stem} pictures the mouse {} pixels tall; {} are painted at \
                 {}x. Re-export it from a larger master.",
                bounds[3],
                largest.round(),
                DENSITIES[DENSITIES.len() - 1]
            );
        }

        let mut bakes = [String::new(), String::new()];
        for (index, painted) in [ENCLOSURE_HEIGHT, THUMBNAIL_HEIGHT].into_iter().enumerate() {
            let densities = &mut bakes[index];
            for scale_factor in DENSITIES {
                let height = (painted * scale_factor).round() as u32;
                let width = (cropped.width() as f32 * height as f32 / cropped.height() as f32)
                    .round() as u32;

                let mut pixels = downsample(cropped.clone(), width, height);
                // GPUI's RenderImage stores straight-alpha BGRA pixels.
                for pixel in pixels.pixels_mut() {
                    pixel.0.swap(0, 2);
                }
                let blob = format!("{stem}@{painted}@{scale_factor}x.bgra");
                fs::write(out_dir.join(&blob), pixels.as_raw()).expect("write baked photo");

                writeln!(
                    densities,
                    "        Baked {{\n            \
                     scale_factor: {scale_factor:?},\n            \
                     width: {width},\n            \
                     height: {height},\n            \
                     bgra: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{blob}\")),\n        \
                 }},"
                )
                .expect("format density");
            }
        }

        let (densities, thumbnails) = (&bakes[0], &bakes[1]);
        writeln!(
            table,
            "const {name}: Photo = Photo {{\n    \
                 densities: &[\n{densities}    ],\n    \
                 thumbnails: &[\n{thumbnails}    ],\n\
             }};"
        )
        .expect("format photo table");
    }

    fs::write(out_dir.join("photos.rs"), table).expect("write photo table");
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=src/filter.rs");
}
