//! Prefilters large device photos into upload-ready sizes at build time.
use std::fmt::Write as _;
use std::{env, fs, path::Path};

include!("src/filter.rs");

/// Common pixel densities, ascending; other densities use the next larger bake.
const DENSITIES: [f32; 2] = [1.0, 2.0];

/// Asset stem, the constant it becomes, and the logical height the app paints
/// it at. This table is the only place those heights are written down.
const PHOTOS: [(&str, &str, f32); 13] = [
    ("pro-x-superlight-black.png", "SUPERLIGHT", 320.0),
    ("pro-x-superlight-white.png", "SUPERLIGHT_WHITE", 320.0),
    ("pro-x-superlight-red.png", "SUPERLIGHT_RED", 320.0),
    ("pro-x-superlight-magenta.png", "SUPERLIGHT_MAGENTA", 320.0),
    ("pro-x-superlight-2-black.png", "SUPERLIGHT_2", 350.0),
    ("pro-x-superlight-2-white.png", "SUPERLIGHT_2_WHITE", 350.0),
    (
        "pro-x-superlight-2-magenta.png",
        "SUPERLIGHT_2_MAGENTA",
        350.0,
    ),
    ("pro-x-superlight-2-cyan.png", "SUPERLIGHT_2_CYAN", 350.0),
    ("g305-lightspeed-black.png", "G305", 350.0),
    ("g305-lightspeed-white.png", "G305_WHITE", 350.0),
    ("g305-lightspeed-blue.png", "G305_BLUE", 350.0),
    ("g305-lightspeed-lilac.png", "G305_LILAC", 350.0),
    ("g305-lightspeed-mint.png", "G305_MINT", 350.0),
];

fn main() {
    let out_dir = env::var("OUT_DIR").expect("cargo sets OUT_DIR");
    let out_dir = Path::new(&out_dir);
    let mut table = String::from("// @generated by build.rs -- do not edit.\n");

    for (stem, name, logical_height) in PHOTOS {
        let source = Path::new("../../assets/mouses").join(stem);
        println!("cargo::rerun-if-changed={}", source.display());

        let master = image::open(&source)
            .unwrap_or_else(|error| panic!("could not read {}: {error}", source.display()))
            .into_rgba32f();

        let mut densities = String::new();
        for scale_factor in DENSITIES {
            let height = (logical_height * scale_factor).round() as u32;
            let width =
                (master.width() as f32 * height as f32 / master.height() as f32).round() as u32;

            let mut pixels = downsample(master.clone(), width, height);
            // GPUI's RenderImage stores straight-alpha BGRA pixels.
            for pixel in pixels.pixels_mut() {
                pixel.0.swap(0, 2);
            }
            let blob = format!("{stem}@{scale_factor}x.bgra");
            fs::write(out_dir.join(&blob), pixels.as_raw()).expect("write baked photo");

            writeln!(
                densities,
                "        Baked {{\n            \
                     scale_factor: {scale_factor:?},\n            \
                     width: {width},\n            \
                     height: {height},\n            \
                     bgra: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{blob}\")),\n        \
                 }},"
            )
            .expect("format density");
        }

        writeln!(
            table,
            "const {name}: Photo = Photo {{\n    \
                 logical_height: {logical_height:?},\n    \
                 densities: &[\n{densities}    ],\n\
             }};"
        )
        .expect("format photo table");
    }

    fs::write(out_dir.join("photos.rs"), table).expect("write photo table");
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=src/filter.rs");
}
