[package]
name = "gflick-agent"
version = "0.1.1"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
build = "build.rs"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
ctrlc.workspace = true
directories.workspace = true
interprocess.workspace = true
gflick-core.workspace = true
gflick-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true

[build-dependencies]
winresource.workspace = true
