[package]
name = "open-hub-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "open-hub"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
clap_complete.workspace = true
open-hub-client.workspace = true
open-hub-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
